<?php
 
$ActionToPageMap = array("accueil" => "formulaires/accueil.php",
	
	"destroy" => "formulaires/accueil.php",
	"login" => "formulaires/login.php",
	"login_client" => "formulaires/login_client.php",
	"login_transporteur" => "formulaires/login_transporteur.php",
	"proposition_tarif" => "formulaires/proposition_tarif.php",
	"inscriptionclient" => "formulaires/inscriptionclient.php",
	"inscriptiontransport" => "formulaires/inscriptiontransport.php",
	"perteidentifiant" => "formulaires/perteidentifiant.php",
	"newpass" => "libs/newpass.php",
	"modiftransporteur" => "formulaires/modiftransporteur.php",
	"modifclient" => "formulaires/modifclient.php",
	"modifmdp" => "formulaires/changermdp.php",
	"demandetransport" => "formulaires/demandetransport.php",
	"demandetransport_divers" => "formulaires/demandetransport_divers.php",
	"demandetransport_valider" => "formulaires/demandetransport_valider.php",
	"modiftransport" => "formulaires/modiftransport.php",
	"supprimetransport" => "formulaires/supprimetransport.php",
	"consulterannonce" => "formulaires/consulterannonce.php",
	"repondreannonce" => "formulaires/repondreannonce1.php",
	"repondreannonce2" => "formulaires/repondreannonce2.php",
	"repondreannonce_valider" => "formulaires/repondreannonce_valider.php",
	"transfert" => "formulaires/transfert.php",
	"dispo" => "formulaires/dispo.php",
	"sejour" => "formulaires/sejour.php",
	"listing_newdemande" => "listing/listing_newdemande.php",
	"listing_newdemande_repondue" => "listing/listing_newdemande_repondue.php",
	"listing_expirer" => "listing/listing_expirer.php",
	"listing_valider_c" => "listing/listing_valider_c.php",
	"listing_valider_t" => "listing/listing_valider_t.php",
	"listing_ancienne_demande" => "listing/listing.php",
	"listing_supprimer" => "listing/listing_supprimer.php",
	"nouveaucontact" => "formulaires/nouveaucontact.php",
	"compare" => "formulaires/compare.php",
	"listing_transporteurs" => "listing/listing_transporteurs.php",
	"accept_offre_transport" => "formulaires/accept_offre_transporteur.php",
	"profil" => "formulaires/profil.php",
	"accept_offre_transport_valider" => "formulaires/accept_offre_transport_valider.php",
	"mesannonces" => "formulaires/mesannonces.php",
	"set_quotation" => "formulaires/set_quotation.php",
	"get_quotation" => "formulaires/get_quotation.php",
	"modif_annonce_transporteur" => "formulaires/modif_annonce_transporteur.php",
	"list_waiting_quotations" => "listing/list_waiting_quotations.php",
	"listing_refuser" => "listing/listing_refuser.php",
	"reglementation" => "formulaires/reglementation.php",
	"faq" => "formulaires/faq.php",
	"commentcamarche" => "formulaires/commentcamarche.php",
	"demonstration" => "formulaires/demonstration.php",
	"listing_transporteur" => "listing/listing_transporteur.php",
	"factures" => "formulaires/factures.php",
	"voirfacturepdf" => "formulaires/voirfacturepdf.php",
	"inscriptionclientredir" => "formulaires/inscriptionclientredir.php",
	"inscriptiontransportredir" => "formulaires/inscriptiontransportredir.php",
	"contact" => "formulaires/contact.php",
	"annulerAnnonce" => "formulaires/annulerAnnonce.php",
	"annulerAnnonce_valider" => "formulaires/annulerAnnonce_valider.php",
	"paypal_init" => "formulaires/paypal_init.php",
	"paypal_notify" => "formulaires/paypal_notify.php",
	"paypal_thx" => "formulaires/paypal_thx.php",
	"file" => "file.php"
	);
	
	include($ActionToPageMap[$action]);
?>